discord:
  # Включена ли привязка к Discord, если вы отключите привязку игроки не смогут подтверждать вход, привязывать аккаунты.
  enabled: false
  # Токен Дискорд бота.
  token: 'discord token here'

  # Пользователи Discord у которых будет админ доступ к привязанным аккаунтам
  # У пользователей с админ-доступом есть возможности:
  # 1. Отвязывать, менять ник, кикать используя обычные команды, и при этом не будет проверки на владение аккаунта.
  # 2. При вводе /adminpanel вам покажет админ панель
  admin-accounts:
    - 123456789 #Сюда ваш id Discord

  # Определяет максимальное количество привязок к одному и тому же дискорду. Поставьте 0 чтобы отключить лимит
  max-discord-link: 0

  # Способы подтверждения привязки аккаунта к соц. сети
  # FROM_GAME - Игрок отправляет запрос с помощью ввода команды в соц. сети, и подтверждает привязку в игре
  # FROM_LINK - Игрок отправляет запрос с помощью ввода команды в игре, и подтверждает привязку в соц. сети
  link-confirm-ways:
    - FROM_LINK

  # Чтобы получить id канала, вы должны включить 'Developer Mode' в настройках. Настройки -> Расширенные -> Режим разработчика.
  # После этого вы должны нажать ПКМ по роли, и нажать 'Копировать ID канала'
  # Белый список каналов. Если какой либо канал указан, кроме этих каналов нельзя будет выполнять команды плагина.
 #whitelist-channels:
 #  - 1234567890123456789

  confirmation:
    # За сколько времени игрок должен привязать аккаунт
    # Время можно указывать в виде:
    # y,г    - год           5y 5г
    # mo,мес - месяц         5mo,5мес
    # w,н    - неделя        5w,5н
    # d,д    - день          5d 5д
    # h,ч    - час           5h 5ч
    # m,м    - минута        5m 5м
    # s,с    - секунды       5с 5s
    # ms,мс  - миллисекунды  5ms 5мс
    # Если не указывать, то по умолчанию секунды
    remove-delay: 120
    code-length: 6
    # Символы которые будут использованы в коде
    code-characters: '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    # Может ли игрок включать/выключать подтверждение
    can-toggle: false
#    # Действия после привязки аккаунта, к примеру выдача или удаление роли.
#    guild-id: 1234567890123456789 # Вы должны указать айди сервера дискорд
#    role-modification:
#      first: # Любое название
#        # Тип события
#        # GIVE_ROLE - Выдача роли
#        # REMOVE_ROLE - Удаление роли
#        type: GIVE_ROLE
#        # Чтобы получить role-id, вы должны включить 'Developer Mode' в настройках. Настройки -> Расширенные -> Режим разработчика.
#        # После этого вы должны нажать ПКМ по роли, и нажать 'Копировать ID роли'
#        role-id: 1234567890123456789
#        # Данная настройка не обязательна, вы можете ее не указывать
#        # При наличии данного пермишшона выдается роль
#        have-permission:
#          - 'group.player'
#        # При отсутствии данного пермишшона выдается роль
#        absent-permission:
#          - 'group.moderator'
#        # ВНИМАНИЕ!!! Если у вас имеется и have-permission, и absent-permission, то для выдачи роли обе должны соотвествовать требованиям!
#      second:
#        # Тип события
#        # GIVE_ROLE - Выдача роли
#        # REMOVE_ROLE - Удаление роли
#        type: REMOVE_ROLE
#        # Чтобы получить role-id, вы должны включить 'Developer Mode' в настройках. Настройки -> Расширенные -> Режим разработчика.
#        # После этого вы должны нажать ПКМ по роли, и нажать 'Копировать ID роли'
#        role-id: 1234567890123456789
#        # Данная настройка не обязательна, вы можете ее не указывать
#        # При наличии данного пермишшона выдается роль
#        have-permission:
#          - 'group.moderator'
#        # При отсутствии данного пермишшона выдается роль
#        absent-permission:
#          - 'group.admin'
#        # ВНИМАНИЕ!!! Если у вас имеется и have-permission, и absent-permission, то для выдачи роли обе должны соотвествовать требованиям!
  enter:
    # За сколько времени игрок должен подтвердить вход в аккаунт
    # Время можно указывать в виде:
    # y,г    - год           5y 5г
    # mo,мес - месяц         5mo,5мес
    # w,н    - неделя        5w,5н
    # d,д    - день          5d 5д
    # h,ч    - час           5h 5ч
    # m,м    - минута        5m 5м
    # s,с    - секунды       5с 5s
    # ms,мс  - миллисекунды  5ms 5мс
    # Если не указывать, то по умолчанию секунды
    enter-delay: 60

  # Настройка кода при восстановлении аккаунта
  restore:
    code-length: 7 # Длина кода
    # Символы которые будут использованы в коде
    code-characters: '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'

  # Команды которые будут в игре, к примеру /adddiscord, или же /code
  proxy-commands:
    link-game: # Указывайте команды БЕЗ знака '/'
      main-command: 'adddiscord'
    code:
      main-command: 'code'

  # Команды в дискорде
  discord-commands: # Основные команды
    link-game:
      main-command: 'adddiscord'
      arguments:
        arg1:
          name: 'name'
          description: 'Player name that we should link'
    enter-accept: # Id команды, не менять!
      main-command: 'accept'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be entered'
    enter-decline:
      main-command: 'decline'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be kicked and declined to enter'
    change-pass:
      main-command: 'changepassword'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that would have changed password'
        arg3:
          name: 'password'
          description: 'New player account password'
    unlink:
      main-command: 'unlink'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be unlinked from Discord'
    accounts:
      main-command: 'accounts'
    account-control:
      main-command: 'control'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be controlled through shown panel'
    kick:
      main-command: 'kick'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be kicked'
    restore:
      main-command: 'restore'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be kicked, and changed password to random one'
    code:
      main-command: 'code'
      arguments:
        arg1:
          name: 'code'
          description: 'Confirmation code for linking account'
    confirmation-toggle:
      main-command: 'toggleconfirmation'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should have toggled confirmation'
    google:
      main-command: 'google'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should have enabled or regenerated TOTP'
    google-code:
      main-command: 'googlecode'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be confirmed'
        arg3:
          name: 'code'
          description: 'TOTP code'
    google-remove:
      main-command: 'googleunlink'
      arguments:
        arg2:
          name: 'name'
          description: 'Player name that should be unlinked from TOTP'
    admin-panel:
      main-command: 'adminpanel'
  # Создание комманд в Discord, пригодится для создания таких команд как: /информация, /help
  custom-commands:
    /help:
      answer: |
        /принять -> Подтверждение входа через Discord \n
        /отклонить -> Отклонение входа через Discord \n
        /отвязать [ник] -> для отвязки аккаунта \n
        /аккаунты -> Контроль аккаунтов через кнопки (Есть система страниц если больше 5 аккаунтов)\n
        /кик [ник] -> Кикнуть игрока с сервера \n
        /восстановить [ник] -> Кикает игрока с сервера если он онлайн, сбрасывает пароль на рандомный, и сбрасывает сессию \n
        /пароль [ник] [новый пароль] -> Меняет пароль аккаунта \n
        /гугл [ник] -> Генерирует гугл-код и QR-Код \n
        /гуглкод [ник] [код] -> Используется при входе с гугл-аутентификацией \n
        /гуглотвязать [ник] -> Отвязывает гугл-аутентификацию \n
        /код (/code) -> Для привязки майнкрафт аккаунта к Discord \n
        /админ-панель,/админпанель,/админ,/панель,/admin-panel,/adminpanel,/admin,/panel -> Можно контролировать привязанные, не привязанные аккаунты
  keyboards:
    confirmation: >
      {
      	"rows": [{
      		"type": 1,
      		"components": [{
      			"type": 2,
      			"label": "Принять",
      			"style": 3,
      			"custom_id": "accept %name%"
      		}, 
            {
      			"type": 2,
      			"label": "Отклонить",
      			"style": 4,
      			"custom_id": "decline %name%"
      		}]
      	}]
      }
    accounts: >  # %account_{index}% - player name, %account_{index}_color% - color that represents is player offline or online
      {
      	"rows": [{
      			"type": 1,
      			"components": [{
      				"type": 2,
      				"label": "%account_1%",
      				"style": "%account_1_color%",
      				"custom_id": "control %account_1%"
      			}]
      		},
      		{
      			"type": 1,
      			"components": [{
      				"type": 2,
      				"label": "%account_2%",
      				"style": "%account_2_color%",
      				"custom_id": "control %account_2%"
      			}]
      		},
      		{
      			"type": 1,
      			"components": [{
      				"type": 2,
      				"label": "%account_3%",
      				"style": "%account_3_color%",
      				"custom_id": "control %account_3%"
      			}]
      		},
      		{
      			"type": 1,
      			"components": [{
      				"type": 2,
      				"label": "%account_4%",
      				"style": "%account_4_color%",
      				"custom_id": "control %account_4%"
      			}]
      		},
      		{
      			"type": 1,
      			"components": [{
      				"type": 2,
      				"label": "<-",
      				"style": "1",
      				"custom_id": "accounts -page %previous_page% -pageSize %pageSize% -type %type%"
      			}, {
      				"type": 2,
      				"label": "->",
      				"style": "1",
      				"custom_id": "accounts -page %next_page% -pageSize %pageSize% -type %type%"
      			}]
      		}
      	]
      }
    account: >
      {
      	"rows": [{
      		"type": 1,
      		"components": [{
      				"type": 2,
      				"label": "Восстановить",
      				"custom_id": "restore %account_name%",
                    "style": 1
      			},
      			{
      				"type": 2,
      				"label": "Кикнуть",
      				"custom_id": "kick %account_name%",
                    "style": 1
      			},
      			{
      				"type": 2,
      				"label": "Отвязать",
      				"custom_id": "unlink %account_name%",
                    "style": 1
      			}
      		]
      	}]
      }
    admin-panel: >
      {
      	"rows": [{
      			"type": 1,
      			"components": [{
      					"type": 2,
      					"label": "Все аккаунты",
      					"custom_id": "accounts -type all",
                        "style": 1
      				},
      				{
      					"type": 2,
      					"label": "Все привязанные аккаунты",
      					"custom_id": "accounts -type linked",
                        "style": 1
      				}
      			]
      		},
      		{
      			"type": 1,
      			"components": [{
      					"type": 2,
      					"label": "Мои аккаунты",
      					"custom_id": "accounts",
                        "style": 1
      				},
      				{
      					"type": 2,
      					"label": "Дискорд аккаунты",
      					"custom_id": "accounts -type local_linked",
                        "style": 1
      				}
      			]
      		}
      	]
      }
  discord-messages: #Для переноса строк используйте "\n" без кавычек.
    forbidden-channel: 'Нельзя выполнять данную команду в этом канале!'
    account-not-found: 'Аккаунт с таким не найден!'
    # Привязка Discord
    confirmation-success: 'Вы успешно привязали аккаунт к Discord'
    already-linked: 'Аккаунт уже привязан к другому Discord!'
    confirmation-sent: 'Всё почти готово. Подтверди привязку в игре через команду: /code %code%'
    confirmation-timed-out: 'Внимание! Время кода истекло. Сгенерируйте его заного'
    confirmation-no-code: '🤔 Произошла ошибка, скорее всего вы ошиблись в вводе кода.\nЧтобы привязать - напишите на сервере /addvk'
    confirmation-not-enough-arguments: 'Вы не указали код! Возможно вы забыли поставить пробел'
    confirmation-role-modification-error: 'Не удалось выдать/убрать роль в Дискорде так как вы не были онлайн, свяжитесь с администрацией!'
    # Переключение подтверждений входа
    confirmation-toggle-disabled: 'Функция отключения подтверждения Discord отключена администрацией.'
    confirmation-toggled: 'Вы успешно переключил подтверждение входа в Discord'
    confirmation-no-player: 'Вы не указали игрока у которого нужно переключить подтверждение входа'
    # Общее
    not-your-account: 'Это не твой аккаунт!'
    # Список аккаунтов
    no-accounts: 'У тебя нету аккаунтов'
    no-page-accounts: 'В данной странице отсутсвуют аккаунты!'
    accounts: 'Твои аккаунты:'
    # Настройка аккаунта
    account-control: 'Настройка аккаунта: %name%'
    # Восстановление аккаунта
    restore-not-enough-arguments: 'Вы не указали ник игрока!'
    restored: 'Теперь пароль от аккаунта %name% - %password%'
    # Кик аккаунта
    kick-not-enough-arguments: 'Вы не указали ник игрока!'
    kick-starting: '✅ Аккаунт %nick% будет кикнут с сервера в течение 5 секунд если он находится на сервере!'
    player-offline: 'ℹ Игрок с ником %nick% не на сервере!'
    kicked: '%nick% был кикнут из сервера'
    # Смена пароля
    changepass-not-enough-arguments: 'Вы не указали ник и пароль игрока!'
    changepass-nothing-to-change: 'Ничего не изменилось!'
    changepass-password-too-short: 'Новый пароль слишком короткий'
    changepass-password-too-long: 'Новый пароль слишком длинный!'
    changepass-success: 'Успешно изменён пароль игрока %name% на %password%'
    # Подтверждение входа через Discord
    enter-no-accounts: 'Вам не отправляли письмо для подтверждения входа 🤔'
    enter-message: '⚠ Попытка авторизации на ваш аккаунт %nick% с IP адреса %account_ip%. Введите /принять или /отклонить, либо нажмите на кнопки'
    enter-declined: 'Вы отменили вход'
    enter-accepted: 'Вы успешно вошли в аккаунт!'
    enter-disabled: 'Вы успешно выключили подтвердение входа! Будьте осторожнее'
    enter-enabled: 'Вы успешно включили подтвердение входа! Теперь вы в безопасности'
    # Отвязка аккаунта Discord
    unlink-not-enough-arguments: 'Вы не указали ник игрока!'
    unlinked: 'Вы успешно отвязали аккаунт %name%'
    # Админ-панель
    admin-panel: 'Админ панель:'
    admin-panel-no-accounts: 'Не найдено аккаунтов!'
    admin-panel-no-linked-accounts: 'Не найдено привязанных аккаунтов!'
    admin-panel-accounts: 'Все аккаунты сервера:'
    admin-panel-linked-accounts: 'Все привязанные аккаунты сервера'
    # Гугл-Код-Аутентификация
    google-disabled: 'Гугл-Аутентификация отключена!'
    google-code-not-enough-arguments: 'Недостаточно аргументов! Правильный ввод: /гугл-код [ник] [код]'
    google-code-not-need-enter: 'Вводить код гугл незачем!'
    google-code-account-not-have-google: 'Ошибка! У аккаунта нету гугл-ключа'
    google-code-account-not-need-enter: 'Вход через гугл аутентификацию не требуется!'
    google-code-not-valid: 'Введенный код неправильный!'
    google-code-valid: 'Введенный код правильный'
    google-code-need-integer: 'Ошибка! Вы должны ввести 6 значную цифру!'
    # Гугл-Генерация
    google-not-enough-arguments: 'Недостаточно аргументов! Правильный ввод: /гугл [ник]'
    google-generated: 'Вы успешно сгенерировали ключ Google-Authenticator: %google_key%'
    google-regenerated: 'Внимание! Вы заного сгенерировали ключ Google Authenticator: %google_key%'
    google-error: 'Произошла ошибка! Сообщите администратору!'
    # Гугл-Отвязка
    google-unlink-not-enough-arguments: 'Недостаточно аргументов! Правильный ввод: /гуглотвязать [ник]'
    google-unlink-not-have-google: 'Ошибка! У аккаунта нету гугл ключа'
    google-unlinked: 'Гугл успешно сброшен!'

    not-enough-permission: 'Недостаточно прав для использования этой команды! Вы должны добавить себя в список админов!'

    unresolved-argument: 'Вы не указали аргумент: %argument_name%'
    unresolved-number: 'Ожидалось число, но вы указали %input%'
    command-invocation: 'При вводе команды произошла ошибка, сообщите администрации'